# vim ft=yaml

os: Visual Studio 2015

environment:
  matrix:
    # Pip builds
    - PYTHON: C:\Python27-x64
    # Conda builds
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86"

build_script:
  - If Defined PY_MAJOR_VER ( tools\appveyor_conda.bat ) else ( tools\appveyor_pip.bat )
  - SET MKL_NUM_THREADS=1
  - SET NUMEXPR_NUM_THREADS=1
  - SET OMP_NUM_THREADS=1
  - pip install "pytest<4" pytest-xdist
  - python setup.py develop
  - echo %PATH%

test_script:
  - echo

on_finish:
  # Note the resulting IP:port address, and use in Microsoft Remote Desktop
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
