# vim ft=yaml

os: Visual Studio 2015

environment:

    matrix:

    - PYTHON: C:\Python27

install:
  # Install Python 3.6.2 if necessary
  - ps: echo "$env:PYTHON"
  - ps: echo "$(& $env:PYTHON\\Python.exe --version)"
  - ps: if ("$(& $env:PYTHON\\Python.exe --version)" -ne "Python 3.6.1") { echo "Foo" }
  - ps: .\install_python362.ps1

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
