# vim ft=yaml

os: Visual Studio 2015

environment:

    matrix:

    - PYTHON: C:\Python27

build: false

test_script:
  # Install Python 3.6.2 if necessary
  - ps: echo "$env:PYTHON"
  - ps: echo "${env:PYTHON}\\Python.exe"
  - ps: echo "$(& ${env:PYTHON}\\Python.exe --version 2> $null)"
  - ps: if ("$(& $env:PYTHON\\Python.exe --version)" -ne "Python 3.6.1") { echo "Foo" }
