# vim ft=yaml

environment:
  global:
      WHEELHOUSE_UPLOADER_USERNAME: travis-worker
      WHEELHOUSE_UPLOADER_SECRET:
        secure:
            9s0gdDGnNnTt7hvyNpn0/ZzOMGPdwPp2SewFTfGzYk7uI+rdAN9rFq2D1gAP4NQh
      PYTHON: C:\Python36

build_script:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

test_script:
  - echo

on_finish:
  # Note the resulting IP:port address, and use in Microsoft Remote Desktop
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
