# vim ft=yaml

os: Visual Studio 2015

environment:
  global:
    OPENBLAS_COMMIT: 2c7392f0
    OPENBLAS_ROOT: c:\opt
    MSYS2_ROOT: c:\msys64

  # Need for mingw-builds discussed at
  # https://github.com/xianyi/OpenBLAS/issues/1503
  # Note spaces instead of %20 in URL, to avoid Windows env var expansion
  matrix:
    - BUILD_BITS: 32
      MINGW_URL: "https://sourceforge.net/projects/mingw-w64/files/Toolchains targetting Win32/Personal Builds/mingw-builds/7.3.0/threads-posix/dwarf/i686-7.3.0-release-posix-dwarf-rt_v5-rev0.7z/download"

# init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: false

test_script:
  - set VC9_ROOT=C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC

  - PATH=%MSYS2_ROOT%\usr\bin;%PATH%
  - echo %MINGW_URL%
  # Get mingw-builds compiler chain, put on path
  - curl -L "%MINGW_URL%" -o mingw_distro.7z
  - 7z x mingw_distro.7z

on_finish:
  # Note the resulting IP:port address, and use in Microsoft Remote Desktop
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
